spring:
  application:
    name: backEnd

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      connectionTimeout: 20000 # 20 seconds
      idleTimeout: 600000 # 10 minutes
      maxLifetime: 1800000 # 30 minutes
      maximumPoolSize: 10
      minimumIdle: 2
      keepaliveTime: 60000 # 1 minute
      poolName: "HikariPool-1"

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        hbm2ddl:
          import_files: students.sql, professors.sql
  h2:
    console:
      enabled: true
      path: /h2-console
