insert into professors (first_name, last_name, subject, phone) values ('Stephenie', 'Ramalho', 'Computer Science', '6014480655');
insert into professors (first_name, last_name, subject, phone) values ('Jody', 'Everson', 'Engineering', '2568093920');
insert into professors (first_name, last_name, subject, phone) values ('Wallas', 'Burnsell', 'Electronics', '8763369338');
insert into professors (first_name, last_name, subject, phone) values ('Selina', 'Stennet', 'Drone Technology', '4649379697');
insert into professors (first_name, last_name, subject, phone) values ('Joanna', 'Bullivent', 'Physics', '3503935191');
insert into professors (first_name, last_name, subject, phone) values ('Marylinda', 'Siverns', 'Math', '8434595327');
insert into professors (first_name, last_name, subject, phone) values ('Gayler', 'Deveraux', 'History', '4904839342');
insert into professors (first_name, last_name, subject, phone) values ('Patrizius', 'Musico', 'Philosophy', '2045706969');
insert into professors (first_name, last_name, subject, phone) values ('Ulrich', 'Paur', 'Mechatronics', '8314535229');
insert into professors (first_name, last_name, subject, phone) values ('Shelley', 'Armfirld', 'Computer Science', '2149813054');
insert into professors (first_name, last_name, subject, phone) values ('Garry', 'Rushbury', 'Engineering', '2382782168');
insert into professors (first_name, last_name, subject, phone) values ('Ethyl', 'Burhill', 'Electronics', '3671955454');
insert into professors (first_name, last_name, subject, phone) values ('Valentine', 'Aldin', 'Drone Technology', '9881473637');
insert into professors (first_name, last_name, subject, phone) values ('Brand', 'Palmer', 'Physics', '5142939075');
insert into professors (first_name, last_name, subject, phone) values ('Joli', 'Raoul', 'Math', '4415081167');
insert into professors (first_name, last_name, subject, phone) values ('Cary', 'Facer', 'History', '2515259446');
insert into professors (first_name, last_name, subject, phone) values ('Della', 'Ardling', 'Philosophy', '8131686345');
insert into professors (first_name, last_name, subject, phone) values ('Ericha', 'Stonehewer', 'Mechatronics', '2702675493');
insert into professors (first_name, last_name, subject, phone) values ('Reuven', 'Dreossi', 'Computer Science', '2029464496');
insert into professors (first_name, last_name, subject, phone) values ('Odie', 'McCollum', 'Engineering', '7227151476');